# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title/


# Setup
title:               Z
tagline:             'NQT'
description:         '.'
url:                 znqt.github.io
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              Z
  url:               https://twitter.com/
  email:             z.nqt225@gmail.com

# Custom vars
version:             1.0.0
